get http://localhost:3000/v1/opportunities


###

post http://localhost:3000/v1/opportunities
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Y2MzYzRiYi1lZDM5LTQ0ODgtOTBlOC1iMzdiNjFmNGFkNTciLCJpYXQiOjE2OTc3MTA3MDF9.tGR4neVVuBzNgvuTwMjHv_DhYfuJ8DRyZz8_ZEsHqjU

{
  "title": "second opportunity",
  "url": "second opportunity url",
  "userId": "5cc3c4bb-ed39-4488-90e8-b37b61f4ad57"
}


###

POST  http://localhost:3000/v1/signup
Content-Type: application/json

{
  "username": "one",
  "firstName": "one",
  "lastName": "one",
  "email": "one@mail.com",
  "password": "123"
}

###

POST http://localhost:3000/v1/signin
Content-Type: application/json

{
  "login": "one@mail.com",
  "password": "123"
}