get http://localhost:3000/opportunities


###

post http://localhost:3000/opportunities
Content-Type: application/json

{
  "title": "first opportunity",
  "url": "first opportunity ul",
  "userId": "1"
}