

name: AzureVM deployer

on:
  push:
    branches: [ deploy-prod ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: checkout repo+branch
        uses: actions/Checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install and build server
        run: |
          cd server
          npm install
          touch src/datastore/sql/motkhss.sqlite
      - name: restart server
        env:
          JWT_SECRET : ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT}}
          PORT: ${{ secrets.PORT }}
          ENV: ${{ secrets.ENV}}
        run: |
          cd server
          npm run start:prod
