

name: AzureVM deployer

on:
  push:
    branches: [ deploy-prod ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo+branch
        uses: actions/checkout@v3

        - name: Deploy and restart web server
          run: |
            cd server
            npm install
            PORT=3000 JWT_SECRET-12345 PASSWORD_SALT=mot ENV=production npm run start:prod