

name: AzureVM deployer

on:
  push:
    branches: [ deploy-prod ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy and restart web server
        env:
          JWT_SECRET : ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT}}
        run: |
          cd server
          npm install
          PORT=80 ENV=production npm run start:prod
