

name: AzureVM deployer

on:
  push:
    branches: [ deploy-prod ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: checkout repo+branch
        uses: actions/Checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: provision database
        run: |
          mkdir -p "$(dirname ${{ secrets.DB_PATH }})"
          touch ${{ secrets.DB_PATH}}
      - name: install and build server
        run: |
          cd server
          npm install
      - name: restart server
        env:
          DB_PATH: ${{secrets.DB_PATH}}
          JWT_SECRET : ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT}}
          PORT: ${{ secrets.PORT }}
          ENV: ${{ secrets.ENV}}
          LOGTAIL_TOKEN: ${{secrets.LOGTAIL_TOKEN}}
          MIXPANEL_TOKEN: ${{secrets.MIXPANEL_TOKEN}}
        run: |
          cd server
          npm run start:prod
